name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        build_type: [Release, Debug]

    name: AppleClang-${{matrix.build_type}}

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: cmake -S . -B build_${{matrix.build_type}}

      - name: Build
        run: cmake --build build_${{matrix.build_type}} --config ${{matrix.build_type}}

      - name: Test
        run: |
          python3 scripts/run-tests.py build_${{matrix.build_type}}/yfc
