name: valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
        mkdir -p cmake
        ./scripts/build.sh
        sudo apt-get update
        sudo apt-get install -y valgrind
    - name: Valgrind
      run: |
        sudo valgrind --error-exitcode=1 --leak-check=full ./cmake/yfc tests/sem/funcs-pass.yf --just-semantics
