name: valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        mkdir -p cmake
        ./scripts/build.sh
    - name: Install Valgrind
      run: |
        sudo apt-get install -y valgrind
    - name: Run Valgrind
      run: |
        sudo valgrind --error-exitcode=1 --leak-check=full ./cmake/yfc tests/sem/funcs-pass.yf
