name: valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        mkdir -p cmake
        ./scripts/build.sh
        sudo apt-get install -y valgrind 
        sudo valgrind --leak-check=full tests/sem/*
